services:
  db:
    image: postgres:17
    container_name: legacy_db
    environment:
      POSTGRES_DB: legacy_payments
      POSTGRES_USER: legacy_user
      POSTGRES_PASSWORD: legacy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./seeder.sql:/docker-entrypoint-initdb.d/02-seeder.sql:ro

  vb:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: legacy_vb
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: legacy_payments
      DB_USER: legacy_user
      DB_PASSWORD: legacy_password
    depends_on:
      - db

volumes:
  postgres_data: